INSERT INTO 'countries' ('code', 'continent_code', 'name', 'iso3', 'number', 'full_name') VALUES
  ('AR', 'SA', 'Argentina', 'ARG', '032', 'Argentine Republic'),
  ('AU', 'OC', 'Australia', 'AUS', '036', 'Commonwealth of Australia'),
  ('AT', 'EU', 'Austria', 'AUT', '040', 'Republic of Austria'),
  ('BE', 'EU', 'Belgium', 'BEL', '056', 'Kingdom of Belgium'),
  ('BR', 'SA', 'Brazil', 'BRA', '076', 'Federative Republic of Brazil'),
  ('BG', 'EU', 'Bulgaria', 'BGR', '100', 'Republic of Bulgaria'),
  ('CA', 'NA', 'Canada', 'CAN', '124', 'Canada'),
  ('CN', 'AS', 'China', 'CHN', '156', 'People Republic of China'),
  ('CO', 'SA', 'Colombia', 'COL', '170', 'Republic of Colombia'),
  ('CU', 'NA', 'Cuba', 'CUB', '192', 'Republic of Cuba'),
  ('CZ', 'EU', 'Czechia', 'CZE', '203', 'Czech Republic'),
  ('EG', 'AF', 'Egypt', 'EGY', '818', 'Arab Republic of Egypt'),
  ('FR', 'EU', 'France', 'FRA', '250', 'French Republic'),
  ('GR', 'EU', 'Greece', 'GRC', '300', 'Hellenic Republic of Greece'),
  ('HK', 'AS', 'Hong Kong', 'HKG', '344', 'Hong Kong Special Administrative Region of China'),
  ('HU', 'EU', 'Hungary', 'HUN', '348', 'Hungary'),
  ('IS', 'EU', 'Iceland', 'ISL', '352', 'Republic of Iceland'),
  ('IN', 'AS', 'India', 'IND', '356', 'Republic of India'),
  ('ID', 'AS', 'Indonesia', 'IDN', '360', 'Republic of Indonesia'),
  ('IR', 'AS', 'Iran', 'IRN', '364', 'Islamic Republic of Iran'),
  ('IQ', 'AS', 'Iraq', 'IRQ', '368', 'Republic of Iraq'),
  ('IE', 'EU', 'Ireland', 'IRL', '372', 'Ireland'),
  ('IL', 'AS', 'Israel', 'ISR', '376', 'State of Israel'),
  ('IT', 'EU', 'Italy', 'ITA', '380', 'Republic of Italy'),
  ('JM', 'NA', 'Jamaica', 'JAM', '388', 'Jamaica'),
  ('JP', 'AS', 'Japan', 'JPN', '392', 'Japan'),
  ('KP', 'AS', 'Korea', 'PRK', '408', 'Democratic People Republic of Korea'),
  ('KR', 'AS', 'Korea', 'KOR', '410', 'Republic of Korea'),
  ('LV', 'EU', 'Latvia', 'LVA', '428', 'Republic of Latvia'),
  ('LT', 'EU', 'Lithuania', 'LTU', '440', 'Republic of Lithuania'),
  ('MY', 'AS', 'Malaysia', 'MYS', '458', 'Malaysia'),
  ('MX', 'NA', 'Mexico', 'MEX', '484', 'United Mexican States'),
  ('NL', 'EU', 'Netherlands', 'NLD', '528', 'Kingdom of the Netherlands'),
  ('NZ', 'OC', 'New Zealand', 'NZL', '554', 'New Zealand'),
  ('NG', 'AF', 'Nigeria', 'NGA', '566', 'Federal Republic of Nigeria'),
  ('NO', 'EU', 'Norway', 'NOR', '578', 'Kingdom of Norway'),
  ('PH', 'AS', 'Philippines', 'PHL', '608', 'Republic of the Philippines'),
  ('PL', 'EU', 'Poland', 'POL', '616', 'Republic of Poland'),
  ('PT', 'EU', 'Portugal', 'PRT', '620', 'Portuguese Republic'),
  ('RO', 'EU', 'Romania', 'ROU', '642', 'Romania'),
  ('RU', 'EU', 'Russian Federation', 'RUS', '643', 'Russian Federation'),
  ('SA', 'AS', 'Saudi Arabia', 'SAU', '682', 'Kingdom of Saudi Arabia'),
  ('SG', 'AS', 'Singapore', 'SGP', '702', 'Republic of Singapore'),
  ('SK', 'EU', 'Slovakia (Slovak Republic)', 'SVK', '703', 'Slovakia (Slovak Republic)'),
  ('SI', 'EU', 'Slovenia', 'SVN', '705', 'Republic of Slovenia'),
  ('SE', 'EU', 'Sweden', 'SWE', '752', 'Kingdom of Sweden'),
  ('CH', 'EU', 'Switzerland', 'CHE', '756', 'Swiss Confederation'),
  ('TW', 'AS', 'Taiwan', 'TWN', '158', 'Taiwan, Province of China'),
  ('TH', 'AS', 'Thailand', 'THA', '764', 'Kingdom of Thailand'),
  ('TR', 'AS', 'Turkey', 'TUR', '792', 'Republic of Turkey'),
  ('UA', 'EU', 'Ukraine', 'UKR', '804', 'Ukraine'),
  ('AE', 'AS', 'United Arab Emirates', 'ARE', '784', 'United Arab Emirates'),
  ('GB', 'EU', 'United Kingdom of Great Britain and Northern Ireland', 'GBR', '826', 'United Kingdom of Great Britain & Northern Ireland'),
  ('US', 'NA', 'United States of America', 'USA', '840', 'United States of America'),
  ('VE', 'SA', 'Venezuela', 'VEN', '862', 'Bolivarian Republic of Venezuela');